---
# Web server configurator
- name: Create matomo php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/matomo.conf
    mode: '0644'
  notify: reload php-fpm

- name: Inject the Matomo site's Nginx configuration
  template:
    src: "matomo.conf.j2"
    dest: "{{ matomo_web_config_dir['available'] }}/matomo.conf"
    owner: "root"
    group: "root"
    mode: "preserve"
    force: true
  notify: reload nginx
  become: true

- name: Enable the site
  file:
    src: "{{ matomo_web_config_file['regular'] }}"
    dest: "{{ matomo_web_config_file['link'] }}"
    state: link
  notify: reload nginx
  become: true
