---
# Application configurator

- name: Create configuration directory for Matomo
  file:
    path: "{{ matomo_path['config'] }}"
    state: directory
    mode: '0755'
  become: true

- name: Inject Matomo's configuration file
  template:
    src: "config.ini.php.j2"
    dest: "{{ matomo_path['config'] }}/config.ini.php"
    owner: "{{ matomo_owner }}"
    group: "{{ matomo_group }}"
    mode: "preserve"
    force: no
  become: true

- name: Create configuration directory for Matomo
  file:
    path: "{{ matomo_path['config'] }}"
    state: directory
    recurse: yes
    mode: '444'
  become: true
